### ISSUE TITLE
Notification to install ACF for Yoast SEO is not cleared

### ISSUE THREAD

**Issue by dariaknl** [Yoast/yoast-acf-analysis#249]
### How can we reproduce this behavior?
1. Install and activate Yoast SEO 14.2 RC1
2. Install and activate Advanced Custom Fields.
3. Check that you see:

<img width="1067" alt="Screenshot 2020-05-15 at 08 32 32" src="https://user-images.githubusercontent.com/19681708/82019004-af5b4600-9686-11ea-8c24-3ecc54042eba.png">

4. Install and activate ACF Content Analysis for Yoast SEO 2.4 RC.
5. Check that you still see notification.

It is expected that it is cleared.

### Technical info
* WordPress version: 5.4.1
* ACF Content Analysis for Yoast SEO version: 2.4RC
* Yoast SEO version: 14.2 RC1
* ACF type: free
* ACF version: 5.8.11 
* Relevant plugins in case of a bug:

**Comment by IreneStr** [comment]
Please base your branch on `release/2.4.0`

**Comment by JesserH** [comment]
This is a duplicate issue and will be fixed in [#15193](https://github.com/Yoast/wordpress-seo/pull/15193)
The problem lies in a incorrect slug of the ACF plugin

**Comment by IreneStr** [comment]
In https://github.com/Yoast/wordpress-seo/pull/15193, which is based on trunk (and therefore will be included in Yoast2 SEO 14.3), we remove the notification entirely.

Like @JesserH wrote above, the problem of the above issue lies in the slug that is used to check whether Yoast ACF is installed.

- In wordpress-seo we have a [class-suggested-plugins](https://github.com/Yoast/wordpress-seo/blob/trunk/admin/class-suggested-plugins.php) in which we set notifications if we detect that certain plugins are active (e.g. ACF) for which we have addons which are not installed/active (e.g Yoast SEO for ACF)
- In order to do so we check in [class-plugin-availability](https://github.com/Yoast/wordpress-seo/blob/trunk/admin/class-plugin-availability.php) which yoast plugins are already installed
- In class-plugin-availability we check whether yoast plugins are installed based on their slug in the plugins folder.
- For ACF we check for [acf-content-analysis-for-yoast-seo/yoast-acf-analysis.php](https://github.com/Yoast/wordpress-seo/blob/trunk/admin/class-plugin-availability.php#L106)
- However, the github repo is called [yoast-acf-analysis](https://github.com/Yoast/yoast-acf-analysis) (not acf-content-analysis-for-yoast-seo)
- This means that when you either checkout the repo from github, or when we create an RC zip, the folder is called `yoast-acf-analysis`. 
    - This means that the check in class-plugin-availability.php will fail, which means that the notification doesn't get removed.
- However, when the plugin is released to WordPress, the folder name is the same as the WordPress plugin repository slug, which is 'acf-content-analysis-for-yoast-seo'. Because that's [how WordPress works](https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#what-will-my-plugin-permalink-slug-be).
    - This means that with a release version, the check in class-plugin-availability.php will succeed, which means that the above issue will not occur in production.
